/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;

import Model.Profile;
import static java.awt.Image.SCALE_DEFAULT;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ZeyuLiao
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Profile profile;
    
    
    public CreateJPanel(Profile product) {
        this.profile = product;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelFName = new javax.swing.JLabel();
        jLabelLName = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelAGE = new javax.swing.JLabel();
        jInputFieldFName = new javax.swing.JTextField();
        jInputFieldLName = new javax.swing.JTextField();
        jInputFieldDOB = new javax.swing.JTextField();
        jInputFieldAge = new javax.swing.JTextField();
        jPanelContact = new javax.swing.JPanel();
        jLabelTEL = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSL1 = new javax.swing.JLabel();
        jLabelSL2 = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelAffiliation = new javax.swing.JLabel();
        jInputFieldTEL = new javax.swing.JTextField();
        jInputFieldEmail = new javax.swing.JTextField();
        jInputFieldSL1 = new javax.swing.JTextField();
        jInputFieldSL2 = new javax.swing.JTextField();
        jInputFieldCity = new javax.swing.JTextField();
        jInputFieldCountry = new javax.swing.JTextField();
        jInputFieldAffiliation = new javax.swing.JTextField();
        jPanelBackground = new javax.swing.JPanel();
        jLabelMajor = new javax.swing.JLabel();
        jLabelCareer = new javax.swing.JLabel();
        jLabelDegree1 = new javax.swing.JLabel();
        jLabelStart1 = new javax.swing.JLabel();
        jLabelEnd1 = new javax.swing.JLabel();
        jLabelDegree2 = new javax.swing.JLabel();
        jLabelStart2 = new javax.swing.JLabel();
        jLabelEnd2 = new javax.swing.JLabel();
        jInputFieldMajor = new javax.swing.JTextField();
        jInputFieldCareer = new javax.swing.JTextField();
        jInputFieldDegree1 = new javax.swing.JTextField();
        jInputFieldStart1 = new javax.swing.JTextField();
        jInputFieldEnd1 = new javax.swing.JTextField();
        jInputFieldDegree2 = new javax.swing.JTextField();
        jInputFieldStart2 = new javax.swing.JTextField();
        jInputFieldEnd2 = new javax.swing.JTextField();
        jPanelPhoto = new javax.swing.JPanel();
        jLabelPhotoArea = new javax.swing.JLabel();
        jLabelPhoto = new javax.swing.JLabel();
        jButtonUpload = new javax.swing.JButton();
        jSaveButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabelTitle.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("New User Registration");
        jLabelTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelFName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelFName.setText("First Name");

        jLabelLName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelLName.setText("Last Name");

        jLabelDOB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDOB.setText("Date of Birth");

        jLabelAGE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelAGE.setText("Age");

        jInputFieldFName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jInputFieldFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldFNameActionPerformed(evt);
            }
        });

        jInputFieldLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldLNameActionPerformed(evt);
            }
        });

        jInputFieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldDOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelFName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(jLabelAGE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInputFieldDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jInputFieldAge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInputFieldLName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInputFieldFName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addComponent(jLabelFName, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addComponent(jInputFieldFName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInputFieldLName)
                        .addGap(4, 4, 4)
                        .addComponent(jInputFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInputFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        jPanelContact.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTEL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTEL.setText("Telephone Number");

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelSL1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSL1.setText("Street Line 1");

        jLabelSL2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSL2.setText("Street Line 2");

        jLabelCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCity.setText("City");

        jLabelCountry.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCountry.setText("Country");

        jLabelAffiliation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelAffiliation.setText("Affiliation");

        jInputFieldTEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldTELActionPerformed(evt);
            }
        });

        jInputFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldEmailActionPerformed(evt);
            }
        });

        jInputFieldSL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldSL1ActionPerformed(evt);
            }
        });

        jInputFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldCityActionPerformed(evt);
            }
        });

        jInputFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldCountryActionPerformed(evt);
            }
        });

        jInputFieldAffiliation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldAffiliationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContactLayout = new javax.swing.GroupLayout(jPanelContact);
        jPanelContact.setLayout(jPanelContactLayout);
        jPanelContactLayout.setHorizontalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContactLayout.createSequentialGroup()
                        .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCountry)
                            .addComponent(jLabelCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContactLayout.createSequentialGroup()
                        .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSL2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jLabelSL1)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelTEL, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)))
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInputFieldAffiliation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jInputFieldSL2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInputFieldCity, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInputFieldCountry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInputFieldTEL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInputFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jInputFieldSL1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanelContactLayout.setVerticalGroup(
            jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContactLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldTEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTEL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jInputFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldSL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSL1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldSL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSL2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCity)
                    .addComponent(jInputFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCountry)
                    .addComponent(jInputFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAffiliation)
                    .addComponent(jInputFieldAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jPanelBackground.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMajor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMajor.setText("Major");

        jLabelCareer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCareer.setText("Career");

        jLabelDegree1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDegree1.setText("Degree 1");

        jLabelStart1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelStart1.setText("Degree 1 Start Date");

        jLabelEnd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEnd1.setText("Degree 1 End Date");

        jLabelDegree2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDegree2.setText("Degree 2");

        jLabelStart2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelStart2.setText("Degree 2 Start Date");

        jLabelEnd2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEnd2.setText("Degree 2 End Date");

        jInputFieldCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldCareerActionPerformed(evt);
            }
        });

        jInputFieldDegree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldDegree1ActionPerformed(evt);
            }
        });

        jInputFieldEnd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldEnd1ActionPerformed(evt);
            }
        });

        jInputFieldDegree2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputFieldDegree2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStart2)
                            .addComponent(jLabelMajor)
                            .addComponent(jLabelStart1)
                            .addComponent(jLabelEnd1)
                            .addComponent(jLabelDegree2)
                            .addComponent(jLabelDegree1)
                            .addComponent(jLabelCareer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jInputFieldMajor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jInputFieldCareer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jInputFieldDegree1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jInputFieldStart1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jInputFieldEnd1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jInputFieldDegree2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jInputFieldStart2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jLabelEnd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jInputFieldEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMajor)
                    .addComponent(jInputFieldMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCareer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldDegree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDegree1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldStart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStart1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldEnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEnd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInputFieldDegree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDegree2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStart2)
                    .addComponent(jInputFieldStart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnd2)
                    .addComponent(jInputFieldEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelPhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPhotoArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelPhoto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelPhoto.setText("Photo");

        jButtonUpload.setText("Upload");
        jButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPhotoLayout = new javax.swing.GroupLayout(jPanelPhoto);
        jPanelPhoto.setLayout(jPanelPhotoLayout);
        jPanelPhotoLayout.setHorizontalGroup(
            jPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPhotoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPhotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonUpload)
                .addGap(42, 42, 42))
        );
        jPanelPhotoLayout.setVerticalGroup(
            jPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhotoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelPhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPhoto)
                    .addComponent(jLabelPhotoArea, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpload)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jSaveButton.setText("SAVE");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jInputFieldFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldFNameActionPerformed

    private void jInputFieldLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldLNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldLNameActionPerformed

    private void jInputFieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldDOBActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        // TODO add your handling code here:
        
        profile.setFirstName(jInputFieldFName.getText());
        profile.setLastName(jInputFieldLName.getText());
        profile.setdOB(jInputFieldDOB.getText());
        profile.setAge(jInputFieldAge.getText());
        profile.setTel(jInputFieldTEL.getText());
        profile.setEmail(jInputFieldEmail.getText());
        profile.setSl1(jInputFieldSL1.getText());
        profile.setSl2(jInputFieldSL2.getText());
        profile.setCity(jInputFieldCity.getText());
        profile.setCountry(jInputFieldCountry.getText());
        profile.setAffiliation(jInputFieldAffiliation.getText());
        profile.setMajor(jInputFieldMajor.getText());
        profile.setCareer(jInputFieldCareer.getText());
        profile.setDg1(jInputFieldDegree1.getText());
        profile.setStart1(jInputFieldStart1.getText());
        profile.setEnd1(jInputFieldEnd1.getText());
        profile.setDg2(jInputFieldDegree2.getText());
        profile.setStart2(jInputFieldStart2.getText());
        profile.setEnd2(jInputFieldEnd2.getText());   
        profile.setImg((ImageIcon) jLabelPhotoArea.getIcon());
        
    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser ch = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("图片","png","jpg");
        ch.setFileFilter(filter);
        
        int ret = ch.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){
            File f = ch.getSelectedFile();
            String fname = f.getAbsolutePath(); 
            ImageIcon img = new ImageIcon(fname);
            img.setImage(img.getImage().getScaledInstance(121,171,SCALE_DEFAULT));
            jLabelPhotoArea.setIcon(img);
        }
    }//GEN-LAST:event_jButtonUploadActionPerformed

    private void jInputFieldTELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldTELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldTELActionPerformed

    private void jInputFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldEmailActionPerformed

    private void jInputFieldSL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldSL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldSL1ActionPerformed

    private void jInputFieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldCityActionPerformed

    private void jInputFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldCountryActionPerformed

    private void jInputFieldAffiliationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldAffiliationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldAffiliationActionPerformed

    private void jInputFieldDegree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldDegree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldDegree1ActionPerformed

    private void jInputFieldCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldCareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldCareerActionPerformed

    private void jInputFieldDegree2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldDegree2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldDegree2ActionPerformed

    private void jInputFieldEnd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputFieldEnd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInputFieldEnd1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonUpload;
    private javax.swing.JTextField jInputFieldAffiliation;
    private javax.swing.JTextField jInputFieldAge;
    private javax.swing.JTextField jInputFieldCareer;
    private javax.swing.JTextField jInputFieldCity;
    private javax.swing.JTextField jInputFieldCountry;
    private javax.swing.JTextField jInputFieldDOB;
    private javax.swing.JTextField jInputFieldDegree1;
    private javax.swing.JTextField jInputFieldDegree2;
    private javax.swing.JTextField jInputFieldEmail;
    private javax.swing.JTextField jInputFieldEnd1;
    private javax.swing.JTextField jInputFieldEnd2;
    private javax.swing.JTextField jInputFieldFName;
    private javax.swing.JTextField jInputFieldLName;
    private javax.swing.JTextField jInputFieldMajor;
    private javax.swing.JTextField jInputFieldSL1;
    private javax.swing.JTextField jInputFieldSL2;
    private javax.swing.JTextField jInputFieldStart1;
    private javax.swing.JTextField jInputFieldStart2;
    private javax.swing.JTextField jInputFieldTEL;
    private javax.swing.JLabel jLabelAGE;
    private javax.swing.JLabel jLabelAffiliation;
    private javax.swing.JLabel jLabelCareer;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelDegree1;
    private javax.swing.JLabel jLabelDegree2;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnd1;
    private javax.swing.JLabel jLabelEnd2;
    private javax.swing.JLabel jLabelFName;
    private javax.swing.JLabel jLabelLName;
    private javax.swing.JLabel jLabelMajor;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelPhotoArea;
    private javax.swing.JLabel jLabelSL1;
    private javax.swing.JLabel jLabelSL2;
    private javax.swing.JLabel jLabelStart1;
    private javax.swing.JLabel jLabelStart2;
    private javax.swing.JLabel jLabelTEL;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelContact;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelPhoto;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

