/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import Model.Profile;
import javax.swing.JOptionPane;

/**
 *
 * @author ZeyuLiao
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Profile profile;
    
    
    public MainJFrame() {
        profile = new Profile();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        JButtonPanel = new javax.swing.JPanel();
        jCreateButton = new javax.swing.JButton();
        jViewButton = new javax.swing.JButton();
        jWorkingArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile Creator");
        setLocation(new java.awt.Point(400, 200));

        jSplitPane1.setDividerLocation(92);

        jCreateButton.setText("Create");
        jCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateButtonActionPerformed(evt);
            }
        });

        jViewButton.setText("View");
        jViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JButtonPanelLayout = new javax.swing.GroupLayout(JButtonPanel);
        JButtonPanel.setLayout(JButtonPanelLayout);
        JButtonPanelLayout.setHorizontalGroup(
            JButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JButtonPanelLayout.setVerticalGroup(
            JButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JButtonPanelLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jCreateButton)
                .addGap(53, 53, 53)
                .addComponent(jViewButton)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(JButtonPanel);

        javax.swing.GroupLayout jWorkingAreaLayout = new javax.swing.GroupLayout(jWorkingArea);
        jWorkingArea.setLayout(jWorkingAreaLayout);
        jWorkingAreaLayout.setHorizontalGroup(
            jWorkingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        jWorkingAreaLayout.setVerticalGroup(
            jWorkingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jWorkingArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateButtonActionPerformed
        // TODO add your handling code here:
        
        CreateJPanel createJPanel = new CreateJPanel(profile);
        jSplitPane1.setRightComponent(createJPanel);
        
        
        
    }//GEN-LAST:event_jCreateButtonActionPerformed

    private void jViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewButtonActionPerformed
        // TODO add your handling code here:
        if(profile.getFirstName()==null){
           JOptionPane.showMessageDialog(null, "Empty Input", "alert", JOptionPane.ERROR_MESSAGE);  
        }
        else{
        ViewJPanel viewJPanel = new ViewJPanel(profile);
        jSplitPane1.setRightComponent(viewJPanel);
        viewJPanel.displayProduct();
            
        }
        
    }//GEN-LAST:event_jViewButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JButtonPanel;
    private javax.swing.JButton jCreateButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jViewButton;
    private javax.swing.JPanel jWorkingArea;
    // End of variables declaration//GEN-END:variables
}
