/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;

import Model.Profile;

/**
 *
 * @author ZeyuLiao
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    Profile profile;
    
    public ViewJPanel(Profile product) {
        this.profile = product;
        initComponents();
    }

    public void displayProduct(){
        jLabelFName.setText(profile.getFirstName());
        jLabelLName.setText(profile.getLastName());
        jLabelDOB.setText("Date of Birth: "+profile.getdOB());
        jLabelAGE.setText("Age: "+profile.getAge()); 
        jLabelTEL.setText("TEL: "+profile.getTel());
        jLabelEmail.setText("Email: "+profile.getEmail());
        jLabelSL1.setText("Address: "+profile.getSl1());
        jLabelSL2.setText(profile.getSl2());
        jLabelCity.setText(profile.getCity());
        jLabelCountry.setText(profile.getCountry());
        jLabelAffiliation.setText("Affiliation: "+profile.getAffiliation());
        jLabelMajor.setText("Major: "+profile.getMajor());
        jLabelCareer.setText("Career: "+profile.getCareer());
        jLabelDegree1.setText("Education: "+profile.getDg1());
        jLabelStart1.setText("From: "+profile.getStart1());
        jLabelEnd1.setText("To: "+profile.getEnd1());
        jLabelDegree2.setText("Education: "+profile.getDg2());
        jLabelStart2.setText("From: "+profile.getStart2());
        jLabelEnd2.setText("To: "+profile.getEnd2());
        jLabelPhoto.setIcon(profile.getImg());
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPhotoPanel = new javax.swing.JPanel();
        jLabelPhoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelFName = new javax.swing.JLabel();
        jLabelLName = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelAGE = new javax.swing.JLabel();
        jLabelTEL = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSL1 = new javax.swing.JLabel();
        jLabelSL2 = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelCountry = new javax.swing.JLabel();
        jLabelAffiliation = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelMajor = new javax.swing.JLabel();
        jLabelCareer = new javax.swing.JLabel();
        jLabelDegree1 = new javax.swing.JLabel();
        jLabelStart1 = new javax.swing.JLabel();
        jLabelEnd1 = new javax.swing.JLabel();
        jLabelDegree2 = new javax.swing.JLabel();
        jLabelStart2 = new javax.swing.JLabel();
        jLabelEnd2 = new javax.swing.JLabel();

        jPhotoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPhotoPanelLayout = new javax.swing.GroupLayout(jPhotoPanel);
        jPhotoPanel.setLayout(jPhotoPanelLayout);
        jPhotoPanelLayout.setHorizontalGroup(
            jPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPhotoPanelLayout.setVerticalGroup(
            jPhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPhotoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelFName.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelFName.setText("First Name");

        jLabelLName.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jLabelLName.setText("Last Name");

        jLabelDOB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDOB.setText("Date of Birth");

        jLabelAGE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelAGE.setText("Age");

        jLabelTEL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTEL.setText("Telephone Number");

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelSL1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSL1.setText("Street Line 1");

        jLabelSL2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelSL2.setText("Street Line 2");

        jLabelCity.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCity.setText("City");

        jLabelCountry.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCountry.setText("Country");

        jLabelAffiliation.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelAffiliation.setText("Affiliation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelFName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelLName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelTEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelSL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSL1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelTEL, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSL1)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSL2)
                    .addComponent(jLabelCity)
                    .addComponent(jLabelCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAffiliation)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMajor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelMajor.setText("Major");

        jLabelCareer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelCareer.setText("Career");

        jLabelDegree1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDegree1.setText("Degree 1");

        jLabelStart1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelStart1.setText("Degree 1 Start Date");

        jLabelEnd1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEnd1.setText("Degree 1 End Date");

        jLabelDegree2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelDegree2.setText("Degree 2");

        jLabelStart2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelStart2.setText("Degree 2 Start Date");

        jLabelEnd2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelEnd2.setText("Degree 2 End Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelDegree1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addComponent(jLabelCareer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelMajor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelDegree2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelStart2, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(jLabelStart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelEnd1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jLabelEnd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMajor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCareer)
                .addGap(18, 18, 18)
                .addComponent(jLabelDegree1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStart1)
                    .addComponent(jLabelEnd1))
                .addGap(29, 29, 29)
                .addComponent(jLabelDegree2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStart2)
                    .addComponent(jLabelEnd2))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPhotoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAGE;
    private javax.swing.JLabel jLabelAffiliation;
    private javax.swing.JLabel jLabelCareer;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelCountry;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelDegree1;
    private javax.swing.JLabel jLabelDegree2;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnd1;
    private javax.swing.JLabel jLabelEnd2;
    private javax.swing.JLabel jLabelFName;
    private javax.swing.JLabel jLabelLName;
    private javax.swing.JLabel jLabelMajor;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JLabel jLabelSL1;
    private javax.swing.JLabel jLabelSL2;
    private javax.swing.JLabel jLabelStart1;
    private javax.swing.JLabel jLabelStart2;
    private javax.swing.JLabel jLabelTEL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPhotoPanel;
    // End of variables declaration//GEN-END:variables
}
